apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jyothi
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        values:
          image.tag: '1.1.0'
          replicaCount: '2'
      - cluster: argo
        url: https://vc-t8lnrrytj8fwb63clf49.zlr-dc1.apps.dev.klusternetes.com
        values:
          image.tag: '1.2.0'
          replicaCount: '3'
      - cluster: argo2
        url: https://vc-7keockut9teuzqzp9cyx.zlr-dc1.apps.dev.klusternetes.com
        values:
          image.tag: '1.3.0'
          replicaCount: '4'
  template:
    metadata:
      name: '{{cluster}}-angular'
    spec:
      project: default
      source:
        repoURL: https://github.com/sai8465/helmchart.git
        targetRevision: HEAD
        path: nodejs
        helm:
          parameters:
          - name: replicaCount
            value: '{{values.replicaCount}}'
          - name: image.tag
            value: '{{values.image.tag}}'

      destination:
        server: '{{url}}'
        namespace: default
